name: Build and Release

on:
  push:
    branches: [ forge-1.20.1, main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ forge-1.20.1, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/libs/*.jar
        if-no-files-found: error
    
    # Create release if this is a tag push
    - name: Get Release Notes
      if: startsWith(github.ref, 'refs/tags/v')
      id: get_release_notes
      run: |
        VERSION="${{ github.ref_name }}"
        NOTES_FILE="RELEASE_NOTES_${VERSION}.md"
        if [ -f "$NOTES_FILE" ]; then
          echo "Using $NOTES_FILE"
          echo "NOTES_FILE=$NOTES_FILE" >> $GITHUB_OUTPUT
        else
          echo "Creating default release notes"
          cat > DEFAULT_NOTES.md << EOF
        # AstroExpansion ${{ github.ref_name }}
        
        This release was automatically generated.
        
        ## Installation
        1. Install Minecraft Forge 1.20.1 (version 47.2.0 or newer)
        2. Download the JAR file below
        3. Place it in your .minecraft/mods folder
        
        ## Requirements
        - Minecraft 1.20.1
        - Forge 47.2.0+
        - Java 17+
        EOF
          echo "NOTES_FILE=DEFAULT_NOTES.md" >> $GITHUB_OUTPUT
        fi
    
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: AstroExpansion ${{ github.ref_name }}
        body_path: ${{ steps.get_release_notes.outputs.NOTES_FILE }}
        files: |
          build/libs/*.jar
          !build/libs/*-sources.jar
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}