name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.1)'
        required: true
        type: string
      release_notes:
        description: 'Release notes'
        required: false
        type: string
        default: 'See RELEASE_NOTES.md for details'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Update version in gradle.properties
      run: |
        sed -i "s/mod_version=.*/mod_version=${{ inputs.version }}/" gradle.properties
        cat gradle.properties
    
    - name: Build with Gradle
      run: ./gradlew clean build
    
    - name: Create Release Notes
      run: |
        cat > RELEASE_NOTES_CURRENT.md << EOF
        # AstroExpansion v${{ inputs.version }}
        
        ${{ inputs.release_notes }}
        
        ## Installation
        1. Install Minecraft Forge 1.20.1 (version 47.2.0 or newer)
        2. Download the JAR file from the assets below
        3. Place it in your .minecraft/mods folder
        
        ## Requirements
        - Minecraft 1.20.1
        - Forge 47.2.0+
        - Java 17+
        EOF
    
    - name: Create Git Tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add gradle.properties
        git commit -m "Release v${{ inputs.version }}" || echo "No changes to commit"
        git tag -a v${{ inputs.version }} -m "Version ${{ inputs.version }}"
        git push origin v${{ inputs.version }}
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ inputs.version }}
        name: AstroExpansion v${{ inputs.version }}
        body_path: RELEASE_NOTES_CURRENT.md
        files: build/libs/astroexpansion-*.jar
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}